// Generated by rstantools.  Do not edit by hand.

/*
    MetaCNMABayes is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MetaCNMABayes is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with MetaCNMABayes.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_binary_fe_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 37> locations_array__ =
  {" (found before start of program)",
  " (in 'binary_fe', line 17, column 2 to column 23)",
  " (in 'binary_fe', line 18, column 2 to column 25)",
  " (in 'binary_fe', line 22, column 25 to column 33)",
  " (in 'binary_fe', line 22, column 10 to column 21)",
  " (in 'binary_fe', line 22, column 2 to column 35)",
  " (in 'binary_fe', line 24, column 14 to column 26)",
  " (in 'binary_fe', line 24, column 2 to column 29)",
  " (in 'binary_fe', line 27, column 4 to column 16)",
  " (in 'binary_fe', line 25, column 28 to line 28, column 3)",
  " (in 'binary_fe', line 25, column 2 to line 28, column 3)",
  " (in 'binary_fe', line 30, column 4 to column 27)",
  " (in 'binary_fe', line 29, column 28 to line 31, column 3)",
  " (in 'binary_fe', line 29, column 2 to line 31, column 3)",
  " (in 'binary_fe', line 33, column 4 to column 28)",
  " (in 'binary_fe', line 35, column 6 to column 57)",
  " (in 'binary_fe', line 36, column 6 to column 46)",
  " (in 'binary_fe', line 34, column 26 to line 37, column 5)",
  " (in 'binary_fe', line 34, column 4 to line 37, column 5)",
  " (in 'binary_fe', line 32, column 24 to line 38, column 3)",
  " (in 'binary_fe', line 32, column 2 to line 38, column 3)",
  " (in 'binary_fe', line 3, column 2 to column 15)",
  " (in 'binary_fe', line 5, column 13 to column 21)",
  " (in 'binary_fe', line 5, column 2 to column 23)",
  " (in 'binary_fe', line 7, column 2 to column 19)",
  " (in 'binary_fe', line 9, column 8 to column 16)",
  " (in 'binary_fe', line 9, column 18 to column 29)",
  " (in 'binary_fe', line 9, column 2 to column 31)",
  " (in 'binary_fe', line 11, column 8 to column 16)",
  " (in 'binary_fe', line 11, column 18 to column 29)",
  " (in 'binary_fe', line 11, column 2 to column 31)",
  " (in 'binary_fe', line 13, column 18 to column 30)",
  " (in 'binary_fe', line 13, column 32 to column 40)",
  " (in 'binary_fe', line 13, column 42 to column 53)",
  " (in 'binary_fe', line 13, column 2 to column 55)",
  " (in 'binary_fe', line 17, column 10 to column 18)",
  " (in 'binary_fe', line 18, column 9 to column 21)"};
#include <stan_meta_header.hpp>
class model_binary_fe final : public model_base_crtp<model_binary_fe> {
private:
  int n_trials;
  std::vector<int> n_arms;
  int n_components;
  std::vector<std::vector<int>> n;
  std::vector<std::vector<int>> r;
  std::vector<std::vector<std::vector<double>>> components;
public:
  ~model_binary_fe() {}
  model_binary_fe(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_binary_fe_namespace::model_binary_fe";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 21;
      context__.validate_dims("data initialization", "n_trials", "int",
        std::vector<size_t>{});
      n_trials = std::numeric_limits<int>::min();
      current_statement__ = 21;
      n_trials = context__.vals_i("n_trials")[(1 - 1)];
      current_statement__ = 22;
      stan::math::validate_non_negative_index("n_arms", "n_trials", n_trials);
      current_statement__ = 23;
      context__.validate_dims("data initialization", "n_arms", "int",
        std::vector<size_t>{static_cast<size_t>(n_trials)});
      n_arms = std::vector<int>(n_trials, std::numeric_limits<int>::min());
      current_statement__ = 23;
      n_arms = context__.vals_i("n_arms");
      current_statement__ = 24;
      context__.validate_dims("data initialization", "n_components", "int",
        std::vector<size_t>{});
      n_components = std::numeric_limits<int>::min();
      current_statement__ = 24;
      n_components = context__.vals_i("n_components")[(1 - 1)];
      current_statement__ = 25;
      stan::math::validate_non_negative_index("n", "n_trials", n_trials);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("n", "max(n_arms)",
        stan::math::max(n_arms));
      current_statement__ = 27;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{static_cast<size_t>(n_trials),
          static_cast<size_t>(stan::math::max(n_arms))});
      n = std::vector<std::vector<int>>(n_trials,
            std::vector<int>(stan::math::max(n_arms),
              std::numeric_limits<int>::min()));
      {
        std::vector<int> n_flat__;
        current_statement__ = 27;
        n_flat__ = context__.vals_i("n");
        current_statement__ = 27;
        pos__ = 1;
        current_statement__ = 27;
        for (int sym1__ = 1; sym1__ <= stan::math::max(n_arms); ++sym1__) {
          current_statement__ = 27;
          for (int sym2__ = 1; sym2__ <= n_trials; ++sym2__) {
            current_statement__ = 27;
            stan::model::assign(n, n_flat__[(pos__ - 1)],
              "assigning variable n", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 27;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 28;
      stan::math::validate_non_negative_index("r", "n_trials", n_trials);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("r", "max(n_arms)",
        stan::math::max(n_arms));
      current_statement__ = 30;
      context__.validate_dims("data initialization", "r", "int",
        std::vector<size_t>{static_cast<size_t>(n_trials),
          static_cast<size_t>(stan::math::max(n_arms))});
      r = std::vector<std::vector<int>>(n_trials,
            std::vector<int>(stan::math::max(n_arms),
              std::numeric_limits<int>::min()));
      {
        std::vector<int> r_flat__;
        current_statement__ = 30;
        r_flat__ = context__.vals_i("r");
        current_statement__ = 30;
        pos__ = 1;
        current_statement__ = 30;
        for (int sym1__ = 1; sym1__ <= stan::math::max(n_arms); ++sym1__) {
          current_statement__ = 30;
          for (int sym2__ = 1; sym2__ <= n_trials; ++sym2__) {
            current_statement__ = 30;
            stan::model::assign(r, r_flat__[(pos__ - 1)],
              "assigning variable r", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 30;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 31;
      stan::math::validate_non_negative_index("components", "n_components",
        n_components);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("components", "n_trials",
        n_trials);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("components", "max(n_arms)",
        stan::math::max(n_arms));
      current_statement__ = 34;
      context__.validate_dims("data initialization", "components", "double",
        std::vector<size_t>{static_cast<size_t>(n_components),
          static_cast<size_t>(n_trials),
          static_cast<size_t>(stan::math::max(n_arms))});
      components = std::vector<std::vector<std::vector<double>>>(n_components,
                     std::vector<std::vector<double>>(n_trials,
                       std::vector<double>(stan::math::max(n_arms),
                         std::numeric_limits<double>::quiet_NaN())));
      {
        std::vector<local_scalar_t__> components_flat__;
        current_statement__ = 34;
        components_flat__ = context__.vals_r("components");
        current_statement__ = 34;
        pos__ = 1;
        current_statement__ = 34;
        for (int sym1__ = 1; sym1__ <= stan::math::max(n_arms); ++sym1__) {
          current_statement__ = 34;
          for (int sym2__ = 1; sym2__ <= n_trials; ++sym2__) {
            current_statement__ = 34;
            for (int sym3__ = 1; sym3__ <= n_components; ++sym3__) {
              current_statement__ = 34;
              stan::model::assign(components, components_flat__[(pos__ - 1)],
                "assigning variable components",
                stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 34;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 35;
      stan::math::validate_non_negative_index("mu", "n_trials", n_trials);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("d", "n_components",
        n_components);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = n_trials + n_components;
  }
  inline std::string model_name() const final {
    return "model_binary_fe";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_binary_fe_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_trials, DUMMY_VAR__);
      current_statement__ = 1;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_trials);
      Eigen::Matrix<local_scalar_t__,-1,1> d =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_components,
          DUMMY_VAR__);
      current_statement__ = 2;
      d = in__.template read<
            Eigen::Matrix<local_scalar_t__,-1,1>>(n_components);
      {
        current_statement__ = 3;
        stan::math::validate_non_negative_index("p", "n_trials", n_trials);
        current_statement__ = 4;
        stan::math::validate_non_negative_index("p", "max(n_arms)",
          stan::math::max(n_arms));
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> p =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(n_trials,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(stan::math::max(
                                                             n_arms),
              DUMMY_VAR__));
        current_statement__ = 6;
        stan::math::validate_non_negative_index("D", "n_components",
          n_components);
        Eigen::Matrix<local_scalar_t__,1,-1> D =
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(n_components,
            DUMMY_VAR__);
        current_statement__ = 10;
        for (int i = 1; i <= n_components; ++i) {
          current_statement__ = 8;
          stan::model::assign(D,
            stan::model::rvalue(d, "d", stan::model::index_uni(i)),
            "assigning variable D", stan::model::index_uni(i));
        }
        current_statement__ = 13;
        for (int i = 1; i <= n_components; ++i) {
          current_statement__ = 11;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(d, "d",
                             stan::model::index_uni(i)), 0, 1000));
        }
        current_statement__ = 20;
        for (int i = 1; i <= n_trials; ++i) {
          current_statement__ = 14;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(mu, "mu",
                             stan::model::index_uni(i)), 0, 1000));
          current_statement__ = 18;
          for (int k = 1; k <=
               stan::model::rvalue(n_arms, "n_arms",
                 stan::model::index_uni(i)); ++k) {
            current_statement__ = 15;
            stan::model::assign(p,
              (stan::model::rvalue(mu, "mu", stan::model::index_uni(i)) +
              stan::math::multiply(D,
                stan::math::to_vector(
                  stan::model::rvalue(components, "components",
                    stan::model::index_omni(), stan::model::index_uni(i),
                    stan::model::index_uni(k))))), "assigning variable p",
              stan::model::index_uni(i), stan::model::index_uni(k));
            current_statement__ = 16;
            lp_accum__.add(stan::math::binomial_logit_lpmf<propto__>(
                             stan::model::rvalue(r, "r",
                               stan::model::index_uni(i),
                               stan::model::index_uni(k)),
                             stan::model::rvalue(n, "n",
                               stan::model::index_uni(i),
                               stan::model::index_uni(k)),
                             stan::model::rvalue(p, "p",
                               stan::model::index_uni(i),
                               stan::model::index_uni(k))));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_binary_fe_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(n_trials,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      mu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_trials);
      Eigen::Matrix<double,-1,1> d =
        Eigen::Matrix<double,-1,1>::Constant(n_components,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      d = in__.template read<
            Eigen::Matrix<local_scalar_t__,-1,1>>(n_components);
      out__.write(mu);
      out__.write(d);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_trials, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_trials),
        "assigning variable mu");
      out__.write(mu);
      Eigen::Matrix<local_scalar_t__,-1,1> d =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_components,
          DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(d,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_components),
        "assigning variable d");
      out__.write(d);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{static_cast<size_t>(n_trials)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "d", "double",
        std::vector<size_t>{static_cast<size_t>(n_components)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_trials, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 1;
        mu_flat__ = context__.vals_r("mu");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= n_trials; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(mu, mu_flat__[(pos__ - 1)],
            "assigning variable mu", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(mu);
      Eigen::Matrix<local_scalar_t__,-1,1> d =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_components,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> d_flat__;
        current_statement__ = 2;
        d_flat__ = context__.vals_r("d");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= n_components; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(d, d_flat__[(pos__ - 1)],
            "assigning variable d", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(d);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "d"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    n_trials)},
                std::vector<size_t>{static_cast<size_t>(n_components)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= n_trials; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_components; ++sym1__) {
      param_names__.emplace_back(std::string() + "d" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= n_trials; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_components; ++sym1__) {
      param_names__.emplace_back(std::string() + "d" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_trials) + "},\"block\":\"parameters\"},{\"name\":\"d\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_components) + "},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_trials) + "},\"block\":\"parameters\"},{\"name\":\"d\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_components) + "},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (n_trials + n_components);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (n_trials + n_components);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_binary_fe_namespace::model_binary_fe;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_binary_fe_namespace::profiles__;
}
#endif
#endif
